builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd
    binary: cercat
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
